django-practices/mysite/ads/urls.py
from django.urls import path, reverse_lazy
from . import views

app_name='ads'
urlpatterns = [
    path('', views.AdListView.as_view(), name='all'),
    path('ads/<int:pk>', views.AdDetailView.as_view(), name='ad_detail'),
    path('ads/create', views.AdCreateView.as_view(success_url=reverse_lazy('ads:all')), name='ad_create'),
    path('ads/<int:pk>/update', views.AdUpdateView.as_view(success_url=reverse_lazy('ads:all')), name='ad_update'),
    path('ads/<int:pk>/delete', views.AdDeleteView.as_view(success_url=reverse_lazy('ads:all')), name='ad_delete'),
]

# We use reverse_lazy in urls.py to delay looking up the view until all the paths are defined

django-practices/mysite/cats/urls.py
from django.urls import path
from django.views.generic import TemplateView
from . import views

app_name ="cats"
urlpatterns = [
    path('', views.MainView.as_view(), name='all'),
    path('main/create', views.CatCreate.as_view(), name='cat_create'),
    path('main/<int:pk>/update', views.CatUpdate.as_view(), name='cat_update'),
    path('main/<int:pk>/delete', views.CatDelete.as_view(), name='cat_delete'),
    path('lookup', views.BreedView.as_view(), name='breed_list'),
    path('lookup/create', views.BreedCreate.as_view(), name='breed_create'),
    path('lookup/<int:pk>/update', views.BreedUpdate.as_view(), name='breed_update'),
    path('lookup/<int:pk>/delete', views.BreedDelete.as_view(), name='breed_delete'),
]

django-practices/mysite/mysite/urls.py
import os
from django.contrib import admin
from django.urls import include, path, re_path
from django.views.static import serve
from django.views.generic import TemplateView

# Up two folders to serve "site" content
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SITE_ROOT = os.path.join(BASE_DIR, 'site')

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
    path('location/',include('location.urls')),
    path('hello/',include('hello_session.urls')),
    path('autos/',include('autos.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('cats/',include('cats.urls')),
    path('', TemplateView.as_view(template_name='home/main.html')),
    re_path(r'^site/(?P<path>.*)$', serve,
        {'document_root': SITE_ROOT, 'show_indexes': True},
        name='site_path'
    ),
]

django-practices/mysite/cats/models.py
from django.db import models
from django.core.validators import MinLengthValidator

class Breed(models.Model):
    name = models.CharField(
        max_length=200,
        help_text='Enter a breed (e.g. Scottish Fold)',
        validators=[MinLengthValidator(2, "Breed must be greater than 1 character")]
    )

    def __str__(self):
        return self.name

class Cat(models.Model):
    nickname = models.CharField(
        max_length=200,
        validators=[MinLengthValidator(2, "Cat's name must be greater than 1 character")]
        )
    weight = models.PositiveIntegerField()
    foods = models.CharField(
        max_length = 300)
    breed = models.ForeignKey('Breed', on_delete = models.CASCADE, null=False)

    def __str__(self):
        return self.nickname

django-practices/mysite/cats/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

from cats.models import Breed, Cat

class MainView(LoginRequiredMixin, View):
    def get(self, request):
        bc = Breed.objects.all().count()
        cl = Cat.objects.all()
        ctx = {'breed_count': bc, 'cat_list': cl}
        return render(request, 'cats/cat_list.html', ctx)

class BreedView(LoginRequiredMixin, View):
    def get(self, request):
        bl = Breed.objects.all()
        ctx = {'breed_list': bl}
        return render(request, 'cats/breed_list.html', ctx)

class BreedCreate(LoginRequiredMixin, CreateView):
    model= Breed
    fields= '__all__'
    success_url = reverse_lazy('cats:breed_list')

class BreedUpdate(LoginRequiredMixin, UpdateView):
    model= Breed
    fields= '__all__'
    success_url = reverse_lazy('cats:breed_list')

class BreedDelete(LoginRequiredMixin, DeleteView):
    model= Breed
    fields= '__all__'
    success_url = reverse_lazy('cats:breed_list')

class CatCreate(LoginRequiredMixin, CreateView):
    model= Cat
    fields= '__all__'
    success_url = reverse_lazy('cats:all')

class CatUpdate(LoginRequiredMixin, UpdateView):
    model= Cat
    fields= '__all__'
    success_url = reverse_lazy('cats:all')

class CatDelete(LoginRequiredMixin, DeleteView):
    model= Cat
    fields= '__all__'
    success_url = reverse_lazy('cats:all')

django-practices/mysite/cats/templates/cats/breed_confirm_delete.html
{% extends "base_bootstrap.html" %}

{% block content %}

<h1>Delete Breed</h1>

<p>Are you sure you want to delete the breed: {{ breed }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
  <input type="submit" onclick="window.location='{% url 'cats:all' %}' ; return false;" value="Cancel">
</form>

{% endblock %}

django-practices/mysite/cats/templates/cats/breed_form.html
{% extends "base_bootstrap.html" %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
    <input type="submit" onclick="window.location='{% url 'cats:all' %}' ; return false;" value="Cancel">
  </form>
{% endblock %}

django-practices/mysite/cats/templates/cats/breed_list.html
{% extends "base_bootstrap.html" %}

{% block content %}
  <h1>Breed List</h1>
    {% if breed_list %}
    <ul>
        {% for breed in breed_list %}
        <li>{{breed.name}}(<a href="{% url 'cats:breed_update' breed.id %}">Update</a>|<a href = "{% url 'cats:breed_delete' breed.id %}">Delete</a>)</li> <br/>
        {% endfor %}
    </ul>
    {% else %}
    <p>You need to add a breed first</p>
    {% endif %}
    <p>
        <a href="{% url 'cats:breed_create' %}">Add a Breed</a>
        <a href="{% url 'cats:all' %}">Back to Cats List</a>
    </p>
{% endblock %}

django-practices/mysite/cats/templates/cats/cat_confirm_delete.html
{% extends "base_bootstrap.html" %}

{% block content %}

<h1>Delete Cat</h1>

<p>Are you sure you want to delete the cat: {{ cat }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
  <input type="submit" onclick="window.location='{% url 'cats:all' %}' ; return false;" value="Cancel">
</form>

{% endblock %}

django-practices/mysite/cats/templates/cats/cat_form.html
{% extends "base_bootstrap.html" %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
    <input type="submit" onclick="window.location='{% url 'cats:all' %}' ; return false;" value="Cancel">
  </form>
{% endblock %}

django-practices/mysite/cats/templates/cats/cat_list.html
{% extends "base_bootstrap.html" %}

{% block content %}
  <h1>Cat List</h1>
    {% if cat_list %}
    <ul>
        {% for cat in cat_list %}
        <li>
            {{ cat.nickname }} ({{ cat.breed }})
            (<a href="{% url 'cats:cat_update' cat.id %}">Update</a> |
          <a href="{% url 'cats:cat_delete' cat.id %}">Delete</a>)) <br/>
            {{ cat.foods }} ({{ cat.weight }} weight)
        </li>
        {% endfor %}
    </ul>
    {% else %}
        <p>There are no cats in the library.</p>
    {% endif %}
    <p>
        {% if breed_count > 0 %}
            <a href="{% url 'cats:cat_create' %}">Add a cat</a>
        {% else %}
            Please add a breed before you add an cat.
        {% endif %}
    </p>
    <p>
        <a href="{% url 'cats:breed_list' %}">View breeds</a>
        <a href="{% url 'cats:breed_create' %}">Add a breed</a>
    </p>
{% endblock %}