django-practices/mysite/ads/urls.py
from django.urls import path, reverse_lazy
from . import views

app_name='ads'
urlpatterns = [
    path('', views.AdListView.as_view(), name='all'),
    path('ads/<int:pk>', views.AdDetailView.as_view(), name='ad_detail'),
    path('ads/create', views.AdCreateView.as_view(success_url=reverse_lazy('ads:all')), name='ad_create'),
    path('ads/<int:pk>/update', views.AdUpdateView.as_view(success_url=reverse_lazy('ads:all')), name='ad_update'),
    path('ads/<int:pk>/delete', views.AdDeleteView.as_view(success_url=reverse_lazy('ads:all')), name='ad_delete'),
]

# We use reverse_lazy in urls.py to delay looking up the view until all the paths are defined

django-practices/mysite/favs/urls.py
from django.urls import path, reverse_lazy
from . import views

# In urls.py reverse_lazy('favs:all')
# In views.py class initialization reverse_lazy('favs:all')
# In views.py methods reverse('favs:all')
# In templates {% url 'favs:thing_update' thing.id %}

app_name='favs'
urlpatterns = [
    path('', views.ThingListView.as_view(), name='all'),
    path('thing/<int:pk>', views.ThingDetailView.as_view(), name='thing_detail'),
    path('thing/create',
        views.ThingCreateView.as_view(success_url=reverse_lazy('favs:all')), name='thing_create'),
    path('thing/<int:pk>/update',
        views.ThingUpdateView.as_view(success_url=reverse_lazy('favs:all')), name='thing_update'),
    path('thing/<int:pk>/delete',
        views.ThingDeleteView.as_view(success_url=reverse_lazy('favs:all')), name='thing_delete'),
    path('thing/<int:pk>/favorite',
        views.AddFavoriteView.as_view(), name='thing_favorite'),
    path('thing/<int:pk>/unfavorite',
        views.DeleteFavoriteView.as_view(), name='thing_unfavorite'),
    path('thing/<int:pk>/comment', views.CommentCreateView.as_view(), name='thing_comment_create'),
    path('thing_picture/<int:pk>', views.stream_file, name='thing_picture'),
    path('comment/<int:pk>/delete', views.CommentDeleteView.as_view(success_url=reverse_lazy('thing:all')), name='thing_comment_delete'),]

django-practices/mysite/mysite/urls.py
import os
from django.contrib import admin
from django.urls import include, path, re_path
from django.views.static import serve
from django.views.generic import TemplateView

# Up two folders to serve "site" content
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SITE_ROOT = os.path.join(BASE_DIR, 'site')

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
    path('location/',include('location.urls')),
    path('hello/',include('hello_session.urls')),
    path('autos/',include('autos.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('cats/',include('cats.urls')),
    path('', TemplateView.as_view(template_name='home/main.html')),
    re_path(r'^site/(?P<path>.*)$', serve,
        {'document_root': SITE_ROOT, 'show_indexes': True},
        name='site_path'
    ),
]

django-practices/mysite/favs/models.py
from django.db import models
from django.core.validators import MinLengthValidator
from django.contrib.auth.models import User
from django.conf import settings
from taggit.managers import TaggableManager

class Thing(models.Model) :
    title = models.CharField(
            max_length=200,
            validators=[MinLengthValidator(2, "Title must be greater than 2 characters")]
    )
    text = models.TextField()
    price = models.DecimalField(max_digits=7, decimal_places=2, null=True)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
            related_name='fav_thing_owner')
    favorites = models.ManyToManyField(settings.AUTH_USER_MODEL,
        through='Fav', related_name='favorite_things')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    picture = models.BinaryField(null=True, blank= True, editable=True)
    content_type = models.CharField(max_length=256, null=True, blank=True, help_text='The MIMEType of the file')
    comment = models.ManyToManyField(settings.AUTH_USER_MODEL, through = "Comment", related_name="forum_comments")
    tags = TaggableManager(blank=True)


    # Shows up in the admin list
    def __str__(self):
        return self.title

class Comment(models.Model) :
    text = models.TextField(
        validators=[MinLengthValidator(3, "Comment must be greater than 3 characters")]
    )

    thing = models.ForeignKey(Thing, on_delete=models.CASCADE, related_name="thing_comment_id")
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        if len(self.text) < 15:
            return self.text
        return self.text[:11]+"..."

class Fav(models.Model) :

    thing = models.ForeignKey(Thing, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
        related_name='favs_users')

    # https://docs.djangoproject.com/en/3.0/ref/models/options/#unique-together
    class Meta:
        unique_together = ('thing', 'user')

    def __str__(self) :
        return '%s likes %s'%(self.user.username, self.thing.title[:10])

django-practices/mysite/favs/forms.py
from django import forms
from favs.models import Thing,Comment
from django.core.files.uploadedfile import InMemoryUploadedFile
from forums.humanize import naturalsize


# Create the form class.
class CreateForm(forms.ModelForm):
    max_upload_limit = 2 * 1024 * 1024
    max_upload_limit_text = naturalsize(max_upload_limit)

    # Call this 'picture' so it gets copied from the form to the in-memory model
    # It will not be the "bytes", it will be the "InMemoryUploadedFile"
    # because we need to pull out things like content_type
    picture = forms.FileField(required=False, label='File to Upload <= '+max_upload_limit_text)
    upload_field_name = 'picture'

    # Hint: this will need to be changed for use in the ads application :)
    class Meta:
        model = Thing
        fields = ['title', 'text', 'price', 'picture', 'tags']  # Picture is manual

    # Validate the size of the picture
    def clean(self):
        cleaned_data = super().clean()
        pic = cleaned_data.get('picture')
        if pic is None:
            return
        if len(pic) > self.max_upload_limit:
            self.add_error('picture', "File must be < "+self.max_upload_limit_text+" bytes")

    # Convert uploaded File object to a picture
    def save(self, commit=True):
        instance = super(CreateForm, self).save(commit=False)

        # We only need to adjust picture if it is a freshly uploaded file
        f = instance.picture   # Make a copy
        if isinstance(f, InMemoryUploadedFile):  # Extract data from the form to the model
            bytearr = f.read()
            instance.content_type = f.content_type
            instance.picture = bytearr  # Overwrite with the actual image data

        if commit:
            instance.save()
            self.save_m2m()

        return instance

class CommentForm(forms.Form):
    comment = forms.CharField(required=True, max_length=500, min_length=3, strip=True)

# https://docs.djangoproject.com/en/3.0/topics/http/file-uploads/
# https://stackoverflow.com/questions/2472422/django-file-upload-size-limit
# https://stackoverflow.com/questions/32007311/how-to-change-data-in-django-modelform
# https://docs.djangoproject.com/en/3.0/ref/forms/validation/#cleaning-and-validating-fields-that-depend-on-each-other

django-practices/mysite/favs/views.py
from favs.models import Thing, Fav, Comment
from favs.forms import CreateForm,CommentForm
from django.views import View
from django.views import generic
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from favs.owner import OwnerListView, OwnerDetailView, OwnerCreateView, OwnerUpdateView, OwnerDeleteView
from django.contrib.humanize.templatetags.humanize import naturaltime

class ThingListView(OwnerListView):
    model = Thing
    template_name = "favs/list.html"

    def get(self, request) :
        strval =  request.GET.get("search", False)
        if strval :
            # Simple title-only search
            # objects = Post.objects.filter(title__contains=strval).select_related().order_by('-updated_at')[:10]

            # Multi-field search
            # __icontains for case-insensitive search
            query = Q(title__icontains=strval)
            query.add(Q(text__icontains=strval), Q.OR)
            query.add(Q(tags__name__in=[strval]), Q.OR)
            thing_list = Thing.objects.filter(query).select_related().order_by('-updated_at')[:10]
        else :
            thing_list = Thing.objects.all().order_by('-updated_at')[:10]

        # Augment the post_list
        for obj in thing_list:
            obj.natural_updated = naturaltime(obj.updated_at)
        favorites = list()
        if request.user.is_authenticated:
            # rows = [{'id': 2}, {'id': 4} ... ]  (A list of rows)
            rows = request.user.favorite_things.values('id')
            # favorites = [2, 4, ...] using list comprehension
            favorites = [ row['id'] for row in rows ]
        ctx = {'thing_list' : thing_list, 'search': strval, 'favorites':favorites}
        return render(request, self.template_name, ctx)

class ThingDetailView(OwnerDetailView):
    model = Thing
    template_name = "favs/detail.html"
    def get(self,request,pk):
        x=Thing.objects.get(id=pk)
        comments=Comment.objects.filter(thing=x).order_by('-updated_at')
        comment_form=CommentForm()
        ctx={'thing':x,'comments':comments,'comment_form':comment_form}
        return render(request,self.template_name,ctx)

class ThingCreateView(LoginRequiredMixin, View):
    template_name = 'favs/form.html'
    success_url = reverse_lazy('thing:all')

    def get(self, request, pk=None):
        form = CreateForm()
        ctx = {'form':form}
        return render(request, self.template_name, ctx)

    def post(self, request, pk=None):
        form = CreateForm(request.POST, request.FILES or None)

        if not form.is_valid():
            ctx={'form':form}
            return render(request,self.template_name,ctx)

        thing = form.save(commit=False)
        thing.owner = self.request.user
        thing.save()
        return redirect(self.success_url)

class ThingUpdateView(LoginRequiredMixin, View):
    template_name = 'favs/form.html'
    success_url = reverse_lazy('thing:all')

    def get(self, request, pk):
        thing=get_object_or_404(Thing, id=pk, owner=self.request.user)
        form=CreateForm(instance=thing)
        ctx={'form':form}
        return render(request, self.template_name,ctx)

    def post(self,request,pk=None):
        thing = get_object_or_404(Thing, id=pk, owner=self.request.user)
        form=CreateForm(request.POST, request.FILES or None, instance=thing)

        if not form.is_valid():
            ctx={'form':form}
            return render(request,self.template_name, ctx)

        thing = form.save(commit=False)
        thing.save()
        return redirect(self.success_url)

class ThingDeleteView(OwnerDeleteView):
    model = Thing
    template_name = "favs/delete.html"

class CommentCreateView(View,LoginRequiredMixin):
    def post(self,request,pk):
        f=get_object_or_404(Thing, id=pk)
        comment = Comment(text=request.POST['comment'], owner=request.user, thing=f)
        comment.save()
        return redirect(reverse('favs:thing_detail', args=[pk]))

class CommentDeleteView(OwnerDeleteView):
    model = Comment
    template_name = "favs/comment_delete.html"

    def get_success_url(self):
        thing = self.object.thing
        return reverse('thing:detail', args=[thing.id])

def stream_file(request, pk):
    thing = get_object_or_404(Thing, id=pk)
    response = HttpResponse()
    response['Content-Type'] = thing.content_type
    response['Content-Length'] = len(thing.picture)
    response.write(thing.picture)
    return response

# csrf exemption in class based views
# https://stackoverflow.com/questions/16458166/how-to-disable-djangos-csrf-validation
from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator
from django.db.utils import IntegrityError

@method_decorator(csrf_exempt, name='dispatch')
class AddFavoriteView(LoginRequiredMixin, View):
    def post(self, request, pk) :
        print("Add PK",pk)
        t = get_object_or_404(Thing, id=pk)
        favorites = Fav(user=request.user, thing=t)
        try:
            favorites.save()  # In case of duplicate key
        except IntegrityError as e:
            pass
        return HttpResponse()

@method_decorator(csrf_exempt, name='dispatch')
class DeleteFavoriteView(LoginRequiredMixin, View):
    def post(self, request, pk) :
        print("Delete PK",pk)
        t = get_object_or_404(Thing, id=pk)
        try:
            favorites = Fav.objects.get(user=request.user, thing=t).delete()
        except Fav.DoesNotExist as e:
            pass

        return HttpResponse()

django-practices/mysite/favs/templates/favs/comment_delete.html
{% extends "base_bootstrap.html" %}
{% block content %}
<h1>Delete Comment</h1>

<p>Are you sure you want to delete</p>
<p>{{ comment.text }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit"  class="btn btn-primary" value="Yes, delete.">
  <a href="{% url 'favs:thing_detail' comment.thing.id %}" class="btn btn-secondary">Cancel</a>
</form>
{% endblock %}

django-practices/mysite/favs/templates/favs/delete.html
{% extends "base_menu.html" %}
{% block content %}
<h1>Delete Thing</h1>

<p>Are you sure you want to delete the thing: {{ thing }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
  <input type="submit" value="Cancel" onclick="window.location.href='{% url 'favs:all' %}';return false;">
</form>
{% endblock %}

django-practices/mysite/favs/templates/favs/detail.html
{% extends "base_menu.html" %}
{% load humanize %} <!-- https://docs.djangoproject.com/en/3.0/ref/contrib/humanize -->
{% load crispy_forms_tags %}
{% block head %}
<style>
.overlay{
  position: fixed;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  z-index: 10;
  display: none;
  background-color: rgba(0,0,0,0.5); /*dim the background*/
}
</style>
{% endblock %}
{% block content %}
{% if thing.content_type %}
<div id="overlay" class="overlay" style="text-align: center;"
   onclick="document.getElementById('overlay').style.display = 'none';" >
<img style="width:90%;margin-top: 50px; border:3px solid black;" src="{% url 'favs:thing_picture' thing.id %}">
</div>
{% endif %}
<span style="float: right;">
({{ thing.updated_at|naturaltime }})
{% if thing.owner == user %}
<a href="{% url 'favs:thing_update' thing.id %}"><i class="fa fa-pencil"></i></a>
<a href="{% url 'favs:thing_delete' thing.id %}"><i class="fa fa-trash"></i></a>
{% endif %}
</span>
<h1>{{ thing.title }}</h1>
{% if thing.tags.all %}
<p>Tags:
  {% for tag in thing.tags.all %}
  <span style="border:1px grey solid; background-color: LightGreen;">{{ tag }}</span>
  {% endfor %}
</p>
{% endif %}
{% if thing.content_type %}
<img style="float:right; max-width:25%;" src="{% url 'favs:thing_picture' thing.id %}"
    onclick="document.getElementById('overlay').style.display = 'block';">
{% endif %}
<p>
{{ thing.text }}
</p>
{% if user.is_authenticated %}
  <form action="{% url 'favs:thing_comment_create' thing.id %}" method="post">
    {% csrf_token %}
    {{ comment_form|crispy }}
    <input type="submit" value="Submit">
    <input type="submit" value="Cancel" onclick="window.location.href='{% url 'favs:all' %}';return false;">
  </form>
{% endif %}
{% for comment in comments %}
<p> {{ comment.text }}
({{ comment.updated_at|naturaltime }})
{% if user == comment.owner %}
<a href="{% url 'favs:thing_comment_delete' comment.id %}"><i class="fa fa-trash"></i></a>
{% endif %}
</p>
{% endfor %}
<p>
<a href="{% url 'favs:all' %}">All Forums</a>
</p>
{% endblock %}

django-practices/mysite/favs/templates/favs/form.html
{% extends "base_menu.html" %}
{% load crispy_forms_tags %}
{% block content %}
<p>
  <form action="" method="post" id="upload_form" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Submit">
    <input type="submit" value="Cancel" onclick="window.location.href='{% url 'favs:all' %}';return false;">
  </form>
</p>
<script>
$("#upload_form").submit(function() {
  console.log('Checking file size');
  if (window.File && window.FileReader && window.FileList && window.Blob) {
      var file = $('#id_{{ form.upload_field_name }}')[0].files[0];
      if (file && file.size > {{ form.max_upload_limit }} ) {
          alert("File " + file.name + " of type " + file.type + " must be < {{ form.max_upload_limit_text }}");
      return false;
    }
  }
});
</script>
{% endblock %}

django-practices/mysite/favs/templates/favs/list.html
{% extends "base_menu.html" %}
{% block content %}
<h1>Favorite Things</h1>
<form>
  <input type="text" placeholder="Search.." name="search"
  {% if search %} value="{{ search }}" {% endif %}
  >
  <button type="submit"><i class="fa fa-search"></i></button>
<a href="{% url 'favs:all' %}"><i class="fa fa-undo"></i></a>
</form>
<p>
{% if thing_list %}
<ul>
  {% for thing in thing_list %}
    <li>
        <a href="{% url 'favs:thing_detail'  thing.id %}">{{ thing.title }}</a>
        {% if thing.owner_id == user.id %}
        (<a href="{% url 'favs:thing_update' thing.id %}">Edit</a> |
        <a href="{% url 'favs:thing_delete' thing.id %}">Delete</a>)
        {% endif %}
        {% if user.is_authenticated %}
        <!-- Two hrefs with two stacked icons each - one showing and one hidden -->
        <a href="#" onclick=
            "favPost('{% url 'favs:thing_unfavorite' thing.id %}', {{ thing.id }} );return false;"
            {% if thing.id not in favorites %} style="display: none;" {% endif %}
            id="favorite_star_{{thing.id}}">
        <span class="fa-stack" style="vertical-align: middle;">
        <i class="fa fa-star fa-stack-1x" style="color: orange;"></i>
        <i class="fa fa-star-o fa-stack-1x"></i>
        </span>
        </a>
        <!-- the second href -->
        <a href="#" onclick=
             "favPost('{% url 'favs:thing_favorite' thing.id %}', {{ thing.id }} );return false;"
            {% if thing.id in favorites %} style="display: none;" {% endif %}
            id="unfavorite_star_{{thing.id}}">
        <span class="fa-stack" style="vertical-align: middle;">
        <i class="fa fa-star fa-stack-1x" style="display: none; color: orange;"></i>
        <i class="fa fa-star-o fa-stack-1x"></i>
        </span>
        </a>
        {% endif %}
        <div style="left:10px">
            {% if post.text|length < 100 %}
                {{ post.text }}
            {% else %}
                {{ post.text|slice:"0:99" }}
                <a href="{% url 'well:post_detail'  post.id %}">...</a>
            {% endif %}
        </div>
        <small>
        {% if thing.owner.username %}
            posted by {{ thing.owner.username }}
        {% endif %}
        {{ thing.natural_updated }}
        </small>
    </li>
  {% endfor %}
</ul>
{% else %}
  <p>There are no things in the database.</p>
{% endif %}
</p>
<p>
<a href="{% url 'favs:thing_create' %}">Add a Thing</a> |
{% if user.is_authenticated %}
<a href="{% url 'logout' %}?next={% url 'favs:all' %}">Logout</a>
{% else %}
<a href="{% url 'login' %}?next={% url 'favs:all' %}">Login</a>
{% endif %}
</p>
<script>
function favPost(url, thing_id) {
    console.log('Requesting JSON');
    $.post(url, {},  function(rowz){
        console.log(url, 'finished');
        $("#unfavorite_star_"+thing_id).toggle();
        $("#favorite_star_"+thing_id).toggle();
    }).fail(function(xhr) {
        alert('Url failed with '+xhr.status+' '+url);
    });
}
</script>
{% endblock %}