django-practices/mysite/ads/urls.py
from django.urls import path, reverse_lazy
from . import views

app_name='ads'
urlpatterns = [
    path('', views.AdListView.as_view(), name='all'),
    path('ads/<int:pk>', views.AdDetailView.as_view(), name='ad_detail'),
    path('ads/create', views.AdCreateView.as_view(success_url=reverse_lazy('ads:all')), name='ad_create'),
    path('ads/<int:pk>/update', views.AdUpdateView.as_view(success_url=reverse_lazy('ads:all')), name='ad_update'),
    path('ads/<int:pk>/delete', views.AdDeleteView.as_view(success_url=reverse_lazy('ads:all')), name='ad_delete'),
]

# We use reverse_lazy in urls.py to delay looking up the view until all the paths are defined

django-practices/mysite/mysite/urls.py
import os
from django.contrib import admin
from django.urls import include, path, re_path
from django.views.static import serve
from django.views.generic import TemplateView

# Up two folders to serve "site" content
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SITE_ROOT = os.path.join(BASE_DIR, 'site')

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
    path('location/',include('location.urls')),
    path('hello/',include('hello_session.urls')),
    path('autos/',include('autos.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('cats/',include('cats.urls')),
    path('', TemplateView.as_view(template_name='home/main.html')),
    re_path(r'^site/(?P<path>.*)$', serve,
        {'document_root': SITE_ROOT, 'show_indexes': True},
        name='site_path'
    ),
]

django-practices/mysite/pics/urls.py
from django.urls import path, reverse_lazy
from . import views

app_name='pics'
urlpatterns = [
    path('', views.PicListView.as_view(), name='all'),
    path('pics/<int:pk>', views.PicDetailView.as_view(), name='pic_detail'),
    path('pics/create', views.PicCreateView.as_view(success_url=reverse_lazy('pics:all')), name='pic_create'),
    path('pics/<int:pk>/update', views.PicUpdateView.as_view(success_url=reverse_lazy('pics:all')), name='pic_update'),
    path('pics/<int:pk>/delete', views.PicDeleteView.as_view(success_url=reverse_lazy('pics:all')), name='pic_delete'),
    path('pics_picture/<int:pk>', views.stream_file, name='pic_picture'),
]

# We use reverse_lazy in urls.py to delay looking up the view until all the paths are defined

django-practices/mysite/pics/models.py
from django.db import models
from django.core.validators import MinLengthValidator
from django.conf import settings

class Pic(models.Model) :
    title = models.CharField(
        max_length=200,
        validators=[MinLengthValidator(2, "Title must be greater than 2 characters")]
    )
    price = models.DecimalField(max_digits=7, decimal_places=2, null=True)
    text = models.TextField()
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    picture = models.BinaryField(null=True, blank= True, editable=True)
    content_type = models.CharField(max_length=256, null=True, blank=True, help_text='The MIMEType of the file')

    def __str__(self):
        return self.title

django-practices/mysite/pics/forms.py
from django import forms
from pics.models import Pic
from django.core.files.uploadedfile import InMemoryUploadedFile
from pics.humanize import naturalsize


# Create the form class.
class CreateForm(forms.ModelForm):
    max_upload_limit = 2 * 1024 * 1024
    max_upload_limit_text = naturalsize(max_upload_limit)

    # Call this 'picture' so it gets copied from the form to the in-memory model
    # It will not be the "bytes", it will be the "InMemoryUploadedFile"
    # because we need to pull out things like content_type
    picture = forms.FileField(required=False, label='File to Upload <= '+max_upload_limit_text)
    upload_field_name = 'picture'

    # Hint: this will need to be changed for use in the ads application :)
    class Meta:
        model = Pic
        fields = ['title', 'text', 'price', 'picture']  # Picture is manual

    # Validate the size of the picture
    def clean(self):
        cleaned_data = super().clean()
        pic = cleaned_data.get('picture')
        if pic is None:
            return
        if len(pic) > self.max_upload_limit:
            self.add_error('picture', "File must be < "+self.max_upload_limit_text+" bytes")

    # Convert uploaded File object to a picture
    def save(self, commit=True):
        instance = super(CreateForm, self).save(commit=False)

        # We only need to adjust picture if it is a freshly uploaded file
        f = instance.picture   # Make a copy
        if isinstance(f, InMemoryUploadedFile):  # Extract data from the form to the model
            bytearr = f.read()
            instance.content_type = f.content_type
            instance.picture = bytearr  # Overwrite with the actual image data

        if commit:
            instance.save()

        return instance

# https://docs.djangoproject.com/en/3.0/topics/http/file-uploads/
# https://stackoverflow.com/questions/2472422/django-file-upload-size-limit
# https://stackoverflow.com/questions/32007311/how-to-change-data-in-django-modelform
# https://docs.djangoproject.com/en/3.0/ref/forms/validation/#cleaning-and-validating-fields-that-depend-on-each-other

django-practices/mysite/pics/views.py
from django.views import View
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.http import HttpResponse
from django.contrib.auth.mixins import LoginRequiredMixin

from pics.owner import OwnerListView, OwnerDetailView, OwnerCreateView, OwnerUpdateView, OwnerDeleteView

from pics.models import Pic
from pics.forms import CreateForm


class PicListView(OwnerListView):
    model = Pic
    template_name = "pics/pic_list.html"


class PicDetailView(OwnerDetailView):
    model = Pic
    template_name = "pics/pic_detail.html"

class PicCreateView(LoginRequiredMixin, View):
    template_name = 'pics/pic_form.html'
    success_url = reverse_lazy('pics:all')

    def get(self, request, pk=None):
        form = CreateForm()
        ctx = {'form':form}
        return render(request, self.template_name, ctx)

    def post(self, request, pk=None):
        form = CreateForm(request.POST, request.FILES or None)

        if not form.is_valid():
            ctx={'form':form}
            return render(request,self.template_name,ctx)

        pic = form.save(commit=False)
        pic.owner = self.request.user
        pic.save()
        return redirect(self.success_url)

class PicUpdateView(LoginRequiredMixin, View):
    template_name = 'pics/pic_form.html'
    success_url = reverse_lazy('pics:all')

    def get(self, request, pk):
        pic=get_object_or_404(Pic, id=pk, owner=self.request.user)
        form=CreateForm(instance=pic)
        ctx={'form':form}
        return render(request, self.template_name,ctx)

    def post(self,request,pk=None):
        pic = get_object_or_404(Pic, id=pk, owner=self.request.user)
        form=CreateForm(request.POST, request.FILES or None, instance=pic)

        if not form.is_valid():
            ctx={'form':form}
            return render(request,self.template_name, ctx)

        pic = form.save(commit=False)
        pic.save()
        return redirect(self.success_url)

class PicDeleteView(OwnerDeleteView):
    model = Pic


def stream_file(request, pk):
    pic = get_object_or_404(Pic, id=pk)
    response = HttpResponse()
    response['Content-Type'] = pic.content_type
    response['Content-Length'] = len(pic.picture)
    response.write(pic.picture)
    return response

django-practices/mysite/pics/templates/pics/pic_confirm_delete.html
{% extends "base_menu.html" %}
{% block content %}
<h1>Delete Ad</h1>

<p>Are you sure you want to delete the ad: {{ pic }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>
{% endblock %}

django-practices/mysite/pics/templates/pics/pic_detail.html
{% extends "base_menu.html" %}
{% load humanize %} <!-- https://docs.djangoproject.com/en/3.0/ref/contrib/humanize -->
{% block head %}
<style>
.overlay{
  position: fixed;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  z-index: 10;
  display: none;
  background-color: rgba(0,0,0,0.5); /*dim the background*/
}
</style>
{% endblock %}
{% block content %}
{% if pic.content_type %}
<div id="overlay" class="overlay" style="text-align: center;"
   onclick="document.getElementById('overlay').style.display = 'none';" >
<img style="width:90%;margin-top: 50px; border:3px solid black;" src="{% url 'pics:pic_picture' pic.id %}">
</div>
{% endif %}
<span style="float: right;">
({{ pic.updated_at|naturaltime }})
{% if pic.owner == user %}
<a href="{% url 'pics:pic_update' pic.id %}"><i class="fa fa-pencil"></i></a>
<a href="{% url 'pics:pic_delete' pic.id %}"><i class="fa fa-trash"></i></a>
{% endif %}
</span>
<h1>{{ pic.title }}</h1>
{% if pic.content_type %}
<img style="float:right; max-width:50%;" src="{% url 'pics:pic_picture' pic.id %}"
    onclick="document.getElementById('overlay').style.display = 'block';">
{% endif %}
<p>
{{ pic.text }}
</p>
<p>
</p>
<p>
<a href="{% url 'pics:all' %}">All pics</a>
</p>
{% endblock %}

django-practices/mysite/pics/templates/pics/pic_form.html
{% extends "base_menu.html" %}
{% load crispy_forms_tags %}
{% block content %}
<p>
  <form action="" method="post" id="upload_form" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Submit">
    <input type="submit" value="Cancel" onclick="window.location.href='{% url 'pics:all' %}';return false;">
  </form>
</p>
<script>
$("#upload_form").submit(function() {
  console.log('Checking file size');
  if (window.File && window.FileReader && window.FileList && window.Blob) {
      var file = $('#id_{{ form.upload_field_name }}')[0].files[0];
      if (file && file.size > {{ form.max_upload_limit }} ) {
          alert("File " + file.name + " of type " + file.type + " must be < {{ form.max_upload_limit_text }}");
      return false;
    }
  }
});
</script>
{% endblock %}

django-practices/mysite/pics/templates/pics/pic_list.html
{% extends "base_menu.html" %}
{% block content %}
<h1>Ad Pics</h1>
<p>
{% if pic_list %}
<ul>
  {% for pic in pic_list %}
    <li>
        <a href="{% url 'pics:pic_detail'  pic.id %}">{{ pic.title }}</a>
        {% if pic.owner == user %}
        (<a href="{% url 'pics:pic_update' pic.id %}">Edit</a> |
        <a href="{% url 'pics:pic_delete' pic.id %}">Delete</a>)
        {% endif %}
        </p>
    </li>
  {% endfor %}
</ul>
{% else %}
  <p>There are no ad in the database.</p>
{% endif %}
</p>
<p>
<a href="{% url 'pics:pic_create' %}">Add an Ad-Pic</a> |
{% if user.is_authenticated %}
<a href="{% url 'logout' %}?next={% url 'pics:all' %}">Logout</a>
{% else %}
<a href="{% url 'login' %}?next={% url 'pics:all' %}">Login</a>
{% endif %}
</p>
{% endblock %}